### ISSUE TITLE
IDEA: Add Support for C4D's Annotation Tag

### ISSUE THREAD

**Issue by donovankeith** [sketchfab/c4d-exporter#12]
Not sure if the API supports this, but Cinema 4D has an annotations tag that could be used to sync annotations between SketchFab and C4D:
http://blog.sketchfab.com/post/92050205754/meet-our-annotations-feature

**Comment by AurL** [comment]
Hi @donovankeith,

Our API doesn't currently support this feature (i.e you can't upload annotations from softwares).
Let's keep this open to keep the idea if the feature becomes available!

Thanks!

**Comment by PadreZippo** [comment]
This plugin is deprecated in favor of https://github.com/sketchfab/c4d-plugin
