### ISSUE TITLE
IDEA: Auto-Open API Token Page

### ISSUE THREAD

**Issue by donovankeith** [sketchfab/c4d-exporter#15]
If I try to upload w/o a valid token, this dialog appears:
![image](https://cloud.githubusercontent.com/assets/4267389/13444725/ca5e5cb0-dfbc-11e5-8d1f-1e13831717fa.png)

Perhaps it should auto-open to the correct page like "Claim your token" does?

**Comment by donovankeith** [comment]
Although, the more I think about it, the more it feels like this whole token business should handled like a sign-in page. You see it the first time as its own window, and then never again after you enter a valid token.

**Comment by PadreZippo** [comment]
This plugin is deprecated in favor of https://github.com/sketchfab/c4d-plugin
