### ISSUE TITLE
ISSUE: Lots of Console Prints

### ISSUE THREAD

**Issue by donovankeith** [sketchfab/c4d-exporter#16]
![image](https://cloud.githubusercontent.com/assets/4267389/13444947/37fefe5e-dfbe-11e5-95a3-0e9d2b083333.png)

Console printing should be reserved for error states for programmer debugging - everything else should be somewhere user-visible like the Status Bar.

In my projects I'll do something like this:

``` python
debug = True

def Upload():
    if debug:
        print "Upload()"

    pass
```

I leave `debug` as `True` when developing, but set it to `False` for all release versions.

**Comment by 990adjustments** [comment]
I agree in cases with large debugging statements but in this case it's not
much debugging as it is informative. Personally, I like the extra bit of
info some pluggins provide.

You might also want to remove my name from there and the copyright as it no
longer applies.

On Tuesday, March 1, 2016, Donovan Keith notifications@github.com wrote:

> [image: image]
> https://cloud.githubusercontent.com/assets/4267389/13444947/37fefe5e-dfbe-11e5-95a3-0e9d2b083333.png
> 
> Console printing should be reserved for error states for programmer
> debugging - everything else should be somewhere user-visible like the
> Status Bar.
> 
> In my projects I'll do something like this:
> 
> debug = True
> def Upload():
>     if debug:
>         print "Upload()"
> 
> ```
> pass
> ```
> 
> I leave debug as True when developing, but set it to False for all
> release versions.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sketchfab/c4d-exporter/issues/16.

## 

Motion Design and Development
990adjustments.com http://www.990adjustments.com/

**Comment by PadreZippo** [comment]
This plugin is deprecated in favor of https://github.com/sketchfab/c4d-plugin
