### ISSUE TITLE
Hard Crash w/ Content Browser Models

### ISSUE THREAD

**Issue by donovankeith** [sketchfab/c4d-exporter#17]
## To Recreate
1. Open C4D
2. Load "CMotion (T-REX).c4d" from the Content Browser
3. Plugins > Sketchfab Exporter
4. `[x] Enable Animation` and `[x] Publish as Draft`
5. Press `Publish`
6. A save dialog will appear.
7. Save to Desktop as "TREX"
8. Process starts, then **HARD CRASH**  
   ![image](https://cloud.githubusercontent.com/assets/4267389/13470961/592196aa-e063-11e5-859e-c57f38a6bd10.png)  
   [_BugReport.txt](https://github.com/sketchfab/c4d-exporter/files/155396/_BugReport.txt)

I think it might have something to do w/ the bones/joints as the same process in a scene w/o animation does not give this result.

**Comment by AurL** [comment]
Hi @donovankeith,

We got a report from a Sketchfab user with the same issue. Maybe the report file will help, attaching it here:
[_BugReport.txt](https://github.com/sketchfab/c4d-exporter/files/436970/_BugReport.txt)

**Comment by PadreZippo** [comment]
This plugin is deprecated in favor of https://github.com/sketchfab/c4d-plugin
