### ISSUE TITLE
Complex Caps / NGons Don't Display Properly in Sketchfab

### ISSUE THREAD

**Issue by donovankeith** [sketchfab/c4d-exporter#18]
**C4D File**
![image](https://cloud.githubusercontent.com/assets/4267389/13471422/5f593076-e065-11e5-8285-c870e5746d58.png)  
[TextUpload.c4d.zip](https://github.com/sketchfab/c4d-exporter/files/155420/TextUpload.c4d.zip)  

**Sketchfab Display**
![image](https://cloud.githubusercontent.com/assets/4267389/13471502/b2673088-e065-11e5-9316-635cd7c720be.png)

Turning on `Triangulate Geometry` in the FBX Exporter fixes this:  
![image](https://cloud.githubusercontent.com/assets/4267389/13471610/1892f4dc-e066-11e5-8c0f-5c94f2c80ac9.png)

Preview:  
![image](https://cloud.githubusercontent.com/assets/4267389/13471637/3e2b244e-e066-11e5-8077-db6b298cf218.png)

Not sure if all exports should be triangulated, but if there aren't any negative side effects, seems like that could make the exporter more robuts.

**Comment by AurL** [comment]
Hi, 

We thought about this several times but the main problem we have with that is that the topology (visible with the wireframe) is important for a part of our users, and we can't actually output them a triangulated version of their work. So the idea here would be to have a better way to tesselate polygons, and it is already logged on our side. 

Once again, thanks for reporting!

**Comment by AurL** [comment]
As we are aware of this problem, let's close the issue

**Comment by donovankeith** [comment]
I'd say the lack of N-Gon support is the issue. Maybe use C4D's native Convert NGons to Triangles command prior to export? That way quad meshes still display as such.

**Comment by PadreZippo** [comment]
This has been resolved by improving tessellation of NGons on our end during processing.

https://sketchfab.com/models/538773a18ca04358b7faf3ad1b9c9d81
