### ISSUE TITLE
BUG: Upload Progress Indicator Frozen at 50%

### ISSUE THREAD

**Issue by donovankeith** [sketchfab/c4d-exporter#19]
When uploading large models with lots of textures, the Upload Indicator starts and is stuck at 50%:  
![image](https://cloud.githubusercontent.com/assets/4267389/13473715/67eb148e-e06f-11e5-875f-8de4c941c011.png)

Expected: Upload progress is indicated in status bar (ideally the SketchFab Exporter dialog), and progress is listed as a % with a time estimate for completion.

`[=====----]`  Uploading: 0.6 MB / 40 MB | Speed: 23 KB/S | ETA: 4 min. 32  sec.

**Comment by PadreZippo** [comment]
This plugin is deprecated in favor of https://github.com/sketchfab/c4d-plugin
