### ISSUE TITLE
IDEA: Auto-Minimize Scenes before Exporting and Uploading

### ISSUE THREAD

**Issue by donovankeith** [sketchfab/c4d-exporter#20]
I've had a number of uploads fail because the scene + textures was too large. For now, you can safely:
1. Delete all sky objects in the scene.
2. Delete any objects not visible in editor/renderer.
3. Remove Unused Materials & Remove Duplicate Materials (Materials Manager > Functions > Remove Unused Materials).

Also, it might be nice to issue some sort of check and warning if the file is going to be too big to upload.
Cheers,

Donovan

**Comment by donovankeith** [comment]
Also, if textures could be auto-converted from .tif to .jpg that would be awesome.

**Comment by AurL** [comment]
Hi @donovankeith, and thanks a lot for these ideas and reports!

I don't answer them separately but I wanted you to know that they are continuously added to our exporter TODO list so that we have everything in mind when working on :)

Thank you very much, and have a nice day!

**Comment by PadreZippo** [comment]
This plugin is deprecated in favor of https://github.com/sketchfab/c4d-plugin
