### ISSUE TITLE
IDEA: Auto-Split or Give Warning if Multiple Materials on One Object

### ISSUE THREAD

**Issue by donovankeith** [sketchfab/c4d-exporter#21]
> FBX
> We don't currently support FBX Layered Textures / composite materials. If a Layered Texture is detected, we choose one layer to display.

[Source](https://help.sketchfab.com/hc/en-us/articles/202600873-Textures-Materials-Formats)

Ideally, the exporter would auto-split the model and apply materials to the split portions. But barring that, please issue a warning and link to information describing how to work around this.

**Comment by PadreZippo** [comment]
This plugin is deprecated in favor of https://github.com/sketchfab/c4d-plugin
