### ISSUE TITLE
User reported issue

### ISSUE THREAD

**Issue by paulchambers3D** [sketchfab/c4d-exporter#23]
Pasted here verbose:

Hi there was just curious if those load issues with the Cinema 4D R17 plugin have been established as yet ? 😕 I know it works for some on previous versions but I'm not having the same luck unfortunately, however I understand it may take some time though as these things do require testing 🙂
MON 1:25PM

Sketchfab
Hi Matt. We're sorry to hear you are currently having issues. We are actively working to resolve them. What operating system, and native language (e.g. English, French etc.) are you using? That will help us.Sent by Paul Chambers
Matt Kelly
Matt
Windows 10, English, 64Bit.
MON 3:16PM

Matt Kelly
Matt
If it may help, The issue may be a SyntaxError in a pyp file as this happend to a google plugin I used once. Thanks all the same 🙂Seen by Matt Kelly at Monday 3:16pm
10:14AM

Sketchfab
Thanks for the extra details Matt. We'll investigate and post updates via our blog and social channels.

**Comment by PadreZippo** [comment]
This plugin is deprecated in favor of https://github.com/sketchfab/c4d-plugin
