### ISSUE TITLE
Crash when exporting

### ISSUE THREAD

**Issue by MAXONRick** [sketchfab/c4d-exporter#3]
I'm getting consistent crashes while trying to upload this file to Sketchfab. I've submitted the crashes to MAXON and am trying to narrow down the culprit.

[farmer_takes2.zip](https://github.com/sketchfab/c4d-exporter/files/105931/farmer_takes2.zip)

**Comment by AurL** [comment]
Hi, 
Thanks for testing and for the repport!

At which step does the crash occur ?
My Cinema4D is not up-to-date, but I tested an upload from my R17.016  (Build RB136011) and had no crash. Here is the model (private): https://sketchfab.com/models/d833ba52c95d4da8857a446f2b93a04e

Note that there is an animation issue: the character has several animation, visible on Sketchfab, but the shotgun has always the same one. When playing animations other that 'Victory', the result is not expected. I have the same result when opening it in Fbx Review. I may have missed a FBX export parameter.

**Comment by MAXONRick** [comment]
Windows 17.048. It's crashing during the export, before upload.

Based on the crash trace from C4D it's crashing in all sorts of different places, which one of our developers tells me is usually the result of modifying the scene structure while it's being accessed. I don't see that happening in your code, but I did notice you're using Python's threading module instead of the threading provided by the C4D api. Not sure if that might be the cause.

**Comment by MAXONRick** [comment]
(hit close accidentally)

**Comment by AurL** [comment]
Hi @MAXONRick, 

Not sure if it's related but a user reported us a crash when using the exporter.
Maybe this log can be useful for you: [_BugReport.txt](https://github.com/sketchfab/c4d-exporter/files/436749/_BugReport.txt)

**Comment by PadreZippo** [comment]
This plugin is deprecated in favor of https://github.com/sketchfab/c4d-plugin
