### ISSUE TITLE
IDEA: Login instead of API Token

### ISSUE THREAD

**Issue by donovankeith** [sketchfab/c4d-exporter#4]
If possible, I would prefer a system that requests a Username & Password in lieu of an API token. If no that, then when I try to submit a model for the first time, it should pop-up a web browser pointed to my API token on my Sketchfab account page. That way it's a more seamless process.
Thanks!

Donovan

**Comment by PadreZippo** [comment]
This plugin is deprecated in favor of https://github.com/sketchfab/c4d-plugin
