### ISSUE TITLE
IDEA: Button to Create a SketchFab Account

### ISSUE THREAD

**Issue by donovankeith** [sketchfab/c4d-exporter#5]
It would be great if the user on-boarding process was a part of this plugin. A new user should be able to setup an account, and upload a model, all from C4D --- or at least they should be directed to the appropriate web-pages to complete the process. Perhaps auto-copy their API key to their clipboard once they're done?
Cheers,

Donovan

**Comment by AurL** [comment]
Creating an account from inside the plugin is not possible for now (as for copying the API token). We added a "Create account" button to redirect the user on the signup page. 

Thanks for the idea, we will improve this in the future if possible!
