### ISSUE TITLE
IDEA: Rename "Auto-publish model" to "Visible to Public Immediately"

### ISSUE THREAD

**Issue by donovankeith** [sketchfab/c4d-exporter#6]
Auto-publish model is a bit ambiguous, it makes me think that I need to click on the checkbox for this plugin to do what it says it's going to do. "Visible to Public Immediately" is a bit clearer.
Thanks,

Donovan

**Comment by AurL** [comment]
Changes has been made here, it's now "Publish as draft (not visible to public immediately)"
Thanks! 
Closing the issue
