### ISSUE TITLE
IDEA: Pop-up "Save Project w/ Assets..." if scene isn't already saved.

### ISSUE THREAD

**Issue by donovankeith** [sketchfab/c4d-exporter#7]
Instead of telling me I should save before uploading, please call the "Save Project with Assets..." command and tell me to save my scene. It saves a step in the process and makes it a bit more seamless.
Cheers,

Donovan

**Comment by AurL** [comment]
Hi, thanks for the idea! It has been added in the latest exporter release.
Closing
