### ISSUE TITLE
IDEA: Option to Replace Existing Draft Model

### ISSUE THREAD

**Issue by donovankeith** [sketchfab/c4d-exporter#9]
If I'm actively testing how a model uploads to SketchFab, I'm going to upload/re-upload on a regular basis. I don't want to create a new model for every one of those most of the time.

Cinema 4D allows you to save data into a document's container, which means that you can load the Filename & Description and Token settings on a per-file basis. I'd recommend doing that.

**Comment by PadreZippo** [comment]
This plugin is deprecated in favor of https://github.com/sketchfab/c4d-plugin
